name: Commit
on:
  push:
  pull_request:
jobs:
  conventional-commit:
    runs-on: ubuntu-latest
    name: Checking commit name
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --ignore-engines
      - name: Run commitlint
        run: yarn commitlint --from=HEAD~1
