name: Commit
on:
  push:
jobs:
  conventional-commit:
    runs-on: ubuntu-latest
    name: Checking commit name
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v4
