name: "CI"
on:
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    name: Checking size
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Check size
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
